// src/utils/regionTranslate.js
// English country/region names → translated names per language
// Keys MUST match the FLAGS keys in flag.js (uppercase)

const TRANSLATIONS = {
  "PAPUA NEW GUINEA":     { vi: "Papua New Guinea",       zh: "巴布亚新几内亚" },
  "UNITED STATES":        { vi: "Hoa Kỳ",                  zh: "美国" },
  "UNITED KINGDOM":       { vi: "Vương quốc Anh",          zh: "英国" },
  "UNITED ARAB EMIRATES": { vi: "UAE",                     zh: "阿联酋" },
  "SAUDI ARABIA":         { vi: "Ả Rập Xê Út",            zh: "沙特阿拉伯" },
  "COSTA RICA":           { vi: "Costa Rica",              zh: "哥斯达黎加" },
  "PUERTO RICO":          { vi: "Puerto Rico",             zh: "波多黎各" },
  "SOUTH AFRICA":         { vi: "Nam Phi",                 zh: "南非" },
  "EL SALVADOR":          { vi: "El Salvador",             zh: "萨尔瓦多" },
  "TRINIDAD AND TOBAGO":  { vi: "Trinidad và Tobago",     zh: "特立尼达和多巴哥" },
  "DOMINICAN REPUBLIC":   { vi: "Cộng hòa Dominica",       zh: "多米尼加共和国" },
  "REPUBLIC OF KOREA":    { vi: "Hàn Quốc",                zh: "韩国" },
  "NORTH KOREA":          { vi: "Triều Tiên",              zh: "朝鲜" },
  "NEW ZEALAND":          { vi: "New Zealand",             zh: "新西兰" },
  "BOSNIA AND HERZEGOVINA":{ vi: "Bosnia & Herzegovina",  zh: "波黑" },
  "SRI LANKA":            { vi: "Sri Lanka",               zh: "斯里兰卡" },
  "CZECH REPUBLIC":       { vi: "Séc",                     zh: "捷克" },
  "SOLOMON ISLANDS":      { vi: "Quần đảo Solomon",       zh: "所罗门群岛" },
  "SIERRA LEONE":         { vi: "Sierra Leone",            zh: "塞拉利昂" },
  "NORTH MACEDONIA":      { vi: "Bắc Macedonia",           zh: "北马其顿" },
  "NORTHERN MARIANA":     { vi: "Bắc Mariana",             zh: "北马里亚纳" },
  "IVORY COAST":          { vi: "Bờ Biển Ngà",             zh: "科特迪瓦" },
  "AFGHANISTAN":          { vi: "Afghanistan",             zh: "阿富汗" },
  "ALBANIA":              { vi: "Albania",                 zh: "阿尔巴尼亚" },
  "ALGERIA":              { vi: "Algérie",                 zh: "阿尔及利亚" },
  "ANGOLA":               { vi: "Angola",                  zh: "安哥拉" },
  "ARGENTINA":            { vi: "Argentina",               zh: "阿根廷" },
  "ARMENIA":              { vi: "Armenia",                 zh: "亚美尼亚" },
  "AUSTRALIA":            { vi: "Úc",                      zh: "澳大利亚" },
  "AUSTRIA":              { vi: "Áo",                      zh: "奥地利" },
  "AZERBAIJAN":           { vi: "Azerbaijan",              zh: "阿塞拜疆" },
  "BAHRAIN":              { vi: "Bahrain",                 zh: "巴林" },
  "BANGLADESH":           { vi: "Bangladesh",              zh: "孟加拉国" },
  "BARBADOS":             { vi: "Barbados",                zh: "巴巴多斯" },
  "BELARUS":              { vi: "Belarus",                 zh: "白俄罗斯" },
  "BELGIUM":              { vi: "Bỉ",                      zh: "比利时" },
  "BOLIVIA":              { vi: "Bolivia",                 zh: "玻利维亚" },
  "BOTSWANA":             { vi: "Botswana",                zh: "博茨瓦纳" },
  "BRAZIL":               { vi: "Brazil",                  zh: "巴西" },
  "BULGARIA":             { vi: "Bulgaria",                zh: "保加利亚" },
  "BURMA":                { vi: "Myanmar",                 zh: "缅甸" },
  "MYANMAR":              { vi: "Myanmar",                 zh: "缅甸" },
  "CAMBODIA":             { vi: "Campuchia",               zh: "柬埔寨" },
  "CAMEROON":             { vi: "Cameroon",                zh: "喀麦隆" },
  "CANADA":               { vi: "Canada",                  zh: "加拿大" },
  "CHILE":                { vi: "Chile",                   zh: "智利" },
  "CHINA":                { vi: "Trung Quốc",             zh: "中国" },
  "COLOMBIA":             { vi: "Colombia",                zh: "哥伦比亚" },
  "CROATIA":              { vi: "Croatia",                 zh: "克罗地亚" },
  "CUBA":                 { vi: "Cuba",                    zh: "古巴" },
  "CYPRUS":               { vi: "Síp",                     zh: "塞浦路斯" },
  "DENMARK":              { vi: "Đan Mạch",               zh: "丹麦" },
  "DOMINICA":             { vi: "Dominica",                zh: "多米尼克" },
  "ECUADOR":              { vi: "Ecuador",                 zh: "厄瓜多尔" },
  "EGYPT":                { vi: "Ai Cập",                  zh: "埃及" },
  "ETHIOPIA":             { vi: "Ethiopia",                zh: "埃塞俄比亚" },
  "FIJI":                 { vi: "Fiji",                    zh: "斐济" },
  "FINLAND":              { vi: "Phần Lan",                zh: "芬兰" },
  "FRANCE":               { vi: "Pháp",                    zh: "法国" },
  "GABON":                { vi: "Gabon",                   zh: "加蓬" },
  "GEORGIA":              { vi: "Georgia",                 zh: "格鲁吉亚" },
  "GERMANY":              { vi: "Đức",                     zh: "德国" },
  "GHANA":                { vi: "Ghana",                   zh: "加纳" },
  "GREECE":               { vi: "Hy Lạp",                  zh: "希腊" },
  "GREENLAND":            { vi: "Greenland",               zh: "格陵兰" },
  "GUATEMALA":            { vi: "Guatemala",               zh: "危地马拉" },
  "GUAM":                 { vi: "Guam",                    zh: "关岛" },
  "GUINEA":               { vi: "Guinea",                  zh: "几内亚" },
  "GUYANA":               { vi: "Guyana",                  zh: "圭亚那" },
  "HAITI":                { vi: "Haiti",                   zh: "海地" },
  "HONDURAS":             { vi: "Honduras",                zh: "洪都拉斯" },
  "HUNGARY":              { vi: "Hungary",                 zh: "匈牙利" },
  "ICELAND":              { vi: "Iceland",                 zh: "冰岛" },
  "INDIA":                { vi: "Ấn Độ",                   zh: "印度" },
  "INDONESIA":            { vi: "Indonesia",               zh: "印度尼西亚" },
  "IRAN":                 { vi: "Iran",                    zh: "伊朗" },
  "IRAQ":                 { vi: "Iraq",                    zh: "伊拉克" },
  "IRELAND":              { vi: "Ireland",                 zh: "爱尔兰" },
  "ISRAEL":               { vi: "Israel",                  zh: "以色列" },
  "ITALY":                { vi: "Ý",                       zh: "意大利" },
  "JAMAICA":              { vi: "Jamaica",                 zh: "牙买加" },
  "JAPAN":                { vi: "Nhật Bản",               zh: "日本" },
  "JORDAN":               { vi: "Jordan",                  zh: "约旦" },
  "KAZAKHSTAN":           { vi: "Kazakhstan",              zh: "哈萨克斯坦" },
  "KENYA":                { vi: "Kenya",                   zh: "肯尼亚" },
  "KYRGYZSTAN":           { vi: "Kyrgyzstan",              zh: "吉尔吉斯斯坦" },
  "KOREA":                { vi: "Hàn Quốc",               zh: "韩国" },
  "KUWAIT":               { vi: "Kuwait",                  zh: "科威特" },
  "LAOS":                 { vi: "Lào",                     zh: "老挝" },
  "LATVIA":               { vi: "Latvia",                  zh: "拉脱维亚" },
  "LEBANON":              { vi: "Lebanon",                 zh: "黎巴嫩" },
  "LIBYA":                { vi: "Libya",                   zh: "利比亚" },
  "LITHUANIA":            { vi: "Lithuania",               zh: "立陶宛" },
  "LUXEMBOURG":           { vi: "Luxembourg",              zh: "卢森堡" },
  "MADAGASCAR":           { vi: "Madagascar",              zh: "马达加斯加" },
  "MALAYSIA":             { vi: "Malaysia",                zh: "马来西亚" },
  "MALDIVES":             { vi: "Maldives",                zh: "马尔代夫" },
  "MALI":                 { vi: "Mali",                    zh: "马里" },
  "MALTA":                { vi: "Malta",                   zh: "马耳他" },
  "MAURITIUS":            { vi: "Mauritius",               zh: "毛里求斯" },
  "MEXICO":               { vi: "México",                  zh: "墨西哥" },
  "MOLDOVA":              { vi: "Moldova",                 zh: "摩尔多瓦" },
  "MONGOLIA":             { vi: "Mông Cổ",                zh: "蒙古" },
  "MONTENEGRO":           { vi: "Montenegro",              zh: "黑山" },
  "MOROCCO":              { vi: "Maroc",                   zh: "摩洛哥" },
  "MOZAMBIQUE":           { vi: "Mozambique",              zh: "莫桑比克" },
  "NAMIBIA":              { vi: "Namibia",                 zh: "纳米比亚" },
  "NEPAL":                { vi: "Nepal",                   zh: "尼泊尔" },
  "NETHERLANDS":          { vi: "Hà Lan",                 zh: "荷兰" },
  "NEW CALEDONIA":        { vi: "Nouvelle-Calédonie",      zh: "新喀里多尼亚" },
  "NICARAGUA":            { vi: "Nicaragua",               zh: "尼加拉瓜" },
  "NIGER":                { vi: "Niger",                   zh: "尼日尔" },
  "NIGERIA":              { vi: "Nigeria",                 zh: "尼日利亚" },
  "NORWAY":               { vi: "Na Uy",                   zh: "挪威" },
  "OMAN":                 { vi: "Oman",                    zh: "阿曼" },
  "PAKISTAN":             { vi: "Pakistan",                zh: "巴基斯坦" },
  "PALAU":                { vi: "Palau",                   zh: "帕劳" },
  "PANAMA":               { vi: "Panama",                  zh: "巴拿马" },
  "PARAGUAY":             { vi: "Paraguay",                zh: "巴拉圭" },
  "PERU":                 { vi: "Peru",                    zh: "秘鲁" },
  "PHILIPPINES":          { vi: "Philippines",             zh: "菲律宾" },
  "POLAND":               { vi: "Ba Lan",                  zh: "波兰" },
  "PORTUGAL":             { vi: "Bồ Đào Nha",             zh: "葡萄牙" },
  "QATAR":                { vi: "Qatar",                   zh: "卡塔尔" },
  "ROMANIA":              { vi: "Romania",                 zh: "罗马尼亚" },
  "RUSSIA":               { vi: "Nga",                     zh: "俄罗斯" },
  "RWANDA":               { vi: "Rwanda",                  zh: "卢旺达" },
  "SAMOA":                { vi: "Samoa",                   zh: "萨摩亚" },
  "SENEGAL":              { vi: "Senegal",                 zh: "塞内加尔" },
  "SERBIA":               { vi: "Serbia",                  zh: "塞尔维亚" },
  "SEYCHELLES":           { vi: "Seychelles",              zh: "塞舌尔" },
  "SINGAPORE":            { vi: "Singapore",               zh: "新加坡" },
  "SLOVAKIA":             { vi: "Slovakia",                zh: "斯洛伐克" },
  "SLOVENIA":             { vi: "Slovenia",                zh: "斯洛文尼亚" },
  "SOMALIA":              { vi: "Somalia",                 zh: "索马里" },
  "SPAIN":                { vi: "Tây Ban Nha",             zh: "西班牙" },
  "SUDAN":                { vi: "Sudan",                   zh: "苏丹" },
  "SURINAME":             { vi: "Suriname",                zh: "苏里南" },
  "SWEDEN":               { vi: "Thụy Điển",              zh: "瑞典" },
  "SWITZERLAND":          { vi: "Thụy Sĩ",                zh: "瑞士" },
  "SYRIA":                { vi: "Syria",                   zh: "叙利亚" },
  "TAIWAN":               { vi: "Đài Loan",               zh: "台湾" },
  "TAJIKISTAN":           { vi: "Tajikistan",              zh: "塔吉克斯坦" },
  "TANZANIA":             { vi: "Tanzania",                zh: "坦桑尼亚" },
  "THAILAND":             { vi: "Thái Lan",               zh: "泰国" },
  "TIBET":                { vi: "Tây Tạng",               zh: "西藏" },
  "TOGO":                 { vi: "Togo",                    zh: "多哥" },
  "TUNISIA":              { vi: "Tunisia",                 zh: "突尼斯" },
  "TURKEY":               { vi: "Thổ Nhĩ Kỳ",            zh: "土耳其" },
  "TURKMENISTAN":         { vi: "Turkmenistan",            zh: "土库曼斯坦" },
  "UGANDA":               { vi: "Uganda",                  zh: "乌干达" },
  "UKRAINE":              { vi: "Ukraina",                 zh: "乌克兰" },
  "URUGUAY":              { vi: "Uruguay",                 zh: "乌拉圭" },
  "UZBEKISTAN":           { vi: "Uzbekistan",              zh: "乌兹别克斯坦" },
  "VANUATU":              { vi: "Vanuatu",                 zh: "瓦努阿图" },
  "VENEZUELA":            { vi: "Venezuela",               zh: "委内瑞拉" },
  "VIETNAM":              { vi: "Việt Nam",               zh: "越南" },
  "YEMEN":                { vi: "Yemen",                   zh: "也门" },
  "ZAMBIA":               { vi: "Zambia",                  zh: "赞比亚" },
  "ZIMBABWE":             { vi: "Zimbabwe",                zh: "津巴布韦" },

  // US states
  "ALASKA":               { vi: "Alaska",                  zh: "阿拉斯加" },
  "HAWAII":               { vi: "Hawaii",                  zh: "夏威夷" },
  "CALIFORNIA":           { vi: "California",              zh: "加利福尼亚" },
  "OREGON":               { vi: "Oregon",                  zh: "俄勒冈" },
  "WASHINGTON":           { vi: "Washington",              zh: "华盛顿" },
  "NEVADA":               { vi: "Nevada",                  zh: "内华达" },
  "MONTANA":              { vi: "Montana",                 zh: "蒙大拿" },
  "IDAHO":                { vi: "Idaho",                   zh: "爱达荷" },
  "WYOMING":              { vi: "Wyoming",                 zh: "怀俄明" },
  "UTAH":                 { vi: "Utah",                    zh: "犹他" },
  "ARIZONA":              { vi: "Arizona",                 zh: "亚利桑那" },
  "NEW MEXICO":           { vi: "New Mexico",              zh: "新墨西哥" },
  "COLORADO":             { vi: "Colorado",                zh: "科罗拉多" },
  "TEXAS":                { vi: "Texas",                   zh: "德克萨斯" },
  "OKLAHOMA":             { vi: "Oklahoma",                zh: "俄克拉荷马" },
  "KANSAS":               { vi: "Kansas",                  zh: "堪萨斯" },
  "NEBRASKA":             { vi: "Nebraska",                zh: "内布拉斯加" },
  "NORTH DAKOTA":         { vi: "Bắc Dakota",              zh: "北达科他" },
  "SOUTH DAKOTA":         { vi: "Nam Dakota",              zh: "南达科他" },
  "MINNESOTA":            { vi: "Minnesota",               zh: "明尼苏达" },
  "IOWA":                 { vi: "Iowa",                    zh: "爱荷华" },
  "MISSOURI":             { vi: "Missouri",                zh: "密苏里" },
  "ARKANSAS":             { vi: "Arkansas",                zh: "阿肯色" },
  "LOUISIANA":            { vi: "Louisiana",               zh: "路易斯安那" },
  "MISSISSIPPI":          { vi: "Mississippi",             zh: "密西西比" },
  "ALABAMA":              { vi: "Alabama",                 zh: "阿拉巴马" },
  "FLORIDA":              { vi: "Florida",                 zh: "佛罗里达" },
  "SOUTH CAROLINA":       { vi: "Bắc Carolina",            zh: "南卡罗来纳" },
  "NORTH CAROLINA":       { vi: "Nam Carolina",            zh: "北卡罗来纳" },
  "TENNESSEE":            { vi: "Tennessee",               zh: "田纳西" },
  "KENTUCKY":             { vi: "Kentucky",                zh: "肯塔基" },
  "VIRGINIA":             { vi: "Virginia",                zh: "弗吉尼亚" },
  "WEST VIRGINIA":        { vi: "Tây Virginia",            zh: "西弗吉尼亚" },
  "MARYLAND":             { vi: "Maryland",                zh: "马里兰" },
  "DELAWARE":             { vi: "Delaware",                zh: "特拉华" },
  "NEW JERSEY":           { vi: "New Jersey",              zh: "新泽西" },
  "PENNSYLVANIA":         { vi: "Pennsylvania",            zh: "宾夕法尼亚" },
  "NEW YORK":             { vi: "New York",                zh: "纽约" },
  "CONNECTICUT":          { vi: "Connecticut",             zh: "康涅狄格" },
  "RHODE ISLAND":         { vi: "Rhode Island",            zh: "罗得岛" },
  "MASSACHUSETTS":        { vi: "Massachusetts",           zh: "马萨诸塞" },
  "VERMONT":              { vi: "Vermont",                 zh: "佛蒙特" },
  "NEW HAMPSHIRE":        { vi: "New Hampshire",           zh: "新罕布什尔" },
  "MAINE":                { vi: "Maine",                   zh: "缅因" },
  "INDIANA":              { vi: "Indiana",                 zh: "印第安纳" },
  "OHIO":                 { vi: "Ohio",                    zh: "俄亥俄" },
  "MICHIGAN":             { vi: "Michigan",                zh: "密歇根" },
  "WISCONSIN":            { vi: "Wisconsin",               zh: "威斯康星" },
  "ILLINOIS":             { vi: "Illinois",                zh: "伊利诺伊" },
  "VIRGIN ISLANDS":       { vi: "Quần đảo Virgin",        zh: "维尔京群岛" },

  // Canadian provinces
  "BRITISH COLUMBIA":     { vi: "British Columbia",        zh: "不列颠哥伦比亚" },
  "ALBERTA":              { vi: "Alberta",                 zh: "阿尔伯塔" },
  "SASKATCHEWAN":         { vi: "Saskatchewan",            zh: "萨斯喀彻温" },
  "MANITOBA":             { vi: "Manitoba",                zh: "曼尼托巴" },
  "ONTARIO":              { vi: "Ontario",                 zh: "安大略" },
  "QUEBEC":               { vi: "Québec",                  zh: "魁北克" },
  "NEW BRUNSWICK":        { vi: "New Brunswick",           zh: "新不伦瑞克" },
  "NOVA SCOTIA":          { vi: "Nova Scotia",             zh: "新斯科舍" },
  "PRINCE EDWARD ISLAND": { vi: "Đảo Hoàng tử Edward",    zh: "爱德华王子岛" },
  "NEWFOUNDLAND":         { vi: "Newfoundland",            zh: "纽芬兰" },
  "YUKON":                { vi: "Yukon",                   zh: "育空" },
  "NORTHWEST TERRITORIES":{ vi: "Lãnh thổ Tây Bắc",       zh: "西北地区" },
  "NUNAVUT":              { vi: "Nunavut",                 zh: "努纳武特" },
};

// Sắp xếp key dài trước để match chính xác (vd: SOUTH CAROLINA trước CAROLINA)
const SORTED_KEYS = Object.keys(TRANSLATIONS).sort((a, b) => b.length - a.length);

function matchesWord(text, name) {
  const pattern = "\\b" + name.replace(/[.*+?^${}()|[\]\\]/g, "\\$&") + "\\b";
  return new RegExp(pattern).test(text);
}

/**
 * Translate a region string (from EMSC/USGS API) to the target language.
 * Only translates country/state names; keeps the rest of the string intact.
 * @param {string} regionText - original text from API
 * @param {string} lang - "vi" | "en" | "zh"
 * @returns {string}
 */
export function translateRegion(regionText, lang) {
  if (!regionText || lang === "en") return regionText;

  const upper = regionText.toUpperCase();

  for (const key of SORTED_KEYS) {
    if (matchesWord(upper, key)) {
      const translated = TRANSLATIONS[key][lang];
      if (!translated) return regionText;
      // Replace the matched country name in the original string (case-insensitive)
      const regex = new RegExp("\\b" + key.replace(/[.*+?^${}()|[\]\\]/g, "\\$&") + "\\b", "i");
      return regionText.replace(regex, translated);
    }
  }

  return regionText;
}
